# Config file (put anything here if used globally)

# Data settings
data_path: "set it"
video_root: "set it"
num_frames: "Extract it"

# Training settings
epochs: "IDk"
batch_size: "Idk"
learning_rate: "idk"
device: "cuda"

# Model settings
clip_model_name: "openai/clip-vit-base-patch32"
checkpoint_dir: "checkpoints/"